name: test_npm_script

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test_npm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install node
      run: nvm install node

    - name: install npm
      run: nvm install-latest-npm
           
    - name: create a website page
      run: |
           npm run build
           npm run serve
