name: test_npm_file

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test_npm_fas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Node.js modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  # 保持稳定且高效的Node.js版本

    - name: Install project dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    # 修改为并行运行两个job，分别对应build和serve命令
    - name: Build
      run: npm run build
      shell: bash
      concurrency: build_and_serve
      env:
        TASK_COMMAND: build

    - name: Serve
      run: npm run serve
      shell: bash
      concurrency: build_and_serve
      env:
        TASK_COMMAND: serve
