name: test_npm_script			# 脚本名称，标识此工作流

on:								        # 触发条件
  push:
    branches: [ "develop" ]		# 向develop分支推送代码时
  pull_request:
    branches: [ "develop" ]

jobs:
  test_npm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install project dependencies
      run: npm install

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-
