name: test_add_file

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  add_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add a file in blog/test_file
      run: mkdir -p blog/test
           touch blog/test/test_file

    - name: Write some data in blog/test_file
      run: echo 123456 > blog/test/test_file
