name: test_npm_script

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test_npm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js and NPM
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        nvm install node

    - name: Install project dependencies
      run: npm install

    - name: Create a website page
      run: |
        npm run build
        npm run serve

